name = input()
surname = input()
animal = input()
sign_of_zodiak = input()
print('Индивидуальный гороскоп для пользователя', name, surname)
print('Кем вы были в прошлой жизни:', animal)
print('Ваш знак зодиака -', sign_of_zodiak, ', поэтому вы - тонко чувствующая натура.')